import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const clashdisplay = localFont({
  src: [
    { path: '../assets/fonts/clashdisplay/ClashDisplay-Extralight.ttf', weight: '200', style: 'normal' },
    { path: '../assets/fonts/clashdisplay/ClashDisplay-Light.ttf', weight: '300', style: 'normal' },
    { path: '../assets/fonts/clashdisplay/ClashDisplay-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../assets/fonts/clashdisplay/ClashDisplay-Medium.ttf', weight: '500', style: 'normal' },
    { path: '../assets/fonts/clashdisplay/ClashDisplay-Semibold.ttf', weight: '600', style: 'normal' },
    { path: '../assets/fonts/clashdisplay/ClashDisplay-Bold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-clashdisplay',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashdisplay.variable} font-clashdisplay  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
